name: Release

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      #   gatsby actions 提供的依赖安装功能不靠谱，进行预先安装
      - name: build
        run: |
          SHARP_IGNORE_GLOBAL_LIBVIPS=true yarn
      - name: gatsby publish
        uses: enriikke/gatsby-gh-pages-action@v2.2.0
        with:
          #    https://github.com/kalencaya personal access tokens, will expire at 2024-01-16
          access-token: x-access-token:${{ secrets.GATSBY_ACCESS_TOKEN }}
          deploy-branch: gh-pages
          gatsby-args: --prefix-paths
          git-config-name: kalencaya
          git-config-email: 1942460489@qq.com
